### PR TITLE
Full featured `SAF` support

### LINKED ISSUE #20: What if persisted document directory get deleted by the user?
**Describe the bug**
In my App, I have selected one directory to store files and then I deleted that directory manually so next time I'll get the URL when I call `persistedUriPermissions` but when I try to add files under that directory it throws the error as directory does not exists which is correct. So What is the solution/workaround for this using which we can identify whether the persisted URL path exists or not?

Even I am not able to find the real path from the Document Tree URL.

**To Reproduce**
1. OpenDocument Tree
2. Save the file on the above path using `createDocumentFile`.
3.  Delete the Directory to which we gave access in step 1 manually. 
4. Next time when we try to store a file we will check any URL available or not in `persistedUriPermissions` and we will find that url in the list.
5. When we try to store the file using the persistedUriPermissions item it will throw an error as Directory does not exist. 

**Expected behavior**
I want a solution/workaround using either We can check the persisted Uri exists or not or I want real path using which I can manually check the directory exists or not.

### PR DESCRIPTION
**Pull request by lakscastro**
## Breaking Changes

Almost everything.

The package started to support only few use-cases (pick a single directory and list granted URIs)

Now the current features are available (See glossary in the end of this doc for a better undestanding):

- [x] Delete file
  - `delete`
- [x] List documents lazily
  - `listFiles`
- [x] List granted URIs
  - `persistedUriPermissions`
- [x] Revoke granted URI
  - `releasePersistableUriPermission`
- [x] Grant URI
  - `openDocumentTree`
- [ ] Grant URI and its subfolders
  - **_Not available yet_** even the first one can read contents recursively of its subfolders (implemented but not available on public APIs)
- [x] Read file content/data
  - `getDocumentContent` `getDocumentContentAsString`
- [ ] Update document content/data
  - **_Not available yet_**
- [x] Update document/directory display name
  - `renameTo`
- [x] Check if a current document/directory is granted or not
  - `canRead`
- [ ] Add broadcast listener to be aware when a Uri permission changes
  - **_Not available yet_**, see #5
- [ ] Be notified when a tree changes (doc deleted, modified, created, etc.)
  - **_Not available yet_**, [check it, can be useful](https://stackoverflow.com/questions/36242311/android-get-documentfile-with-write-access-for-any-file-path-on-sd-card-havin) and [here either even it's legacy](http://www.java2s.com/Open-Source/Android_Free_Code/Example/course/com_toraleap_collimator_utilRecursiveFileObserver_java.htm)
- [ ] Restrict mimetypes of `openDocumentTree` API
  - **_Not available yet_**
- [ ] Add Open document file API from `openDocument` native method
  - **_Not available yet_**
- [ ] Full database query support (sort, cursor, projection, etc.)
  - **_Not available yet_**, [need complement, see ref/impl](https://github.com/lakscastro/shared-storage/blob/e295b0f800cdc30e6519263bd761fc9945f5f25e/android/src/main/kotlin/io/lakscastro/sharedstorage/saf/utils/DocumentCommon.kt#L182-L190)
- [ ] Fix #20 
- [ ] Investigate #22 
- [ ] Add file conflict resolution methods
  - **_Not available yet_**

https://github.com/lakscastro/shared-storage/blob/e295b0f800cdc30e6519263bd761fc9945f5f25e/android/src/main/kotlin/io/lakscastro/sharedstorage/saf/utils/DocumentCommon.kt#L182-L189

## Glossary

- Consider **document** equal to **file**
- **URIs** are instances of `java.net.Uri` class that represents the location of a document in the tree, can be a file/document or a directory itself
- **Lazily** is a kind of optimization, in this case a **heavy optimization**, because the native Android method (`listFiles` cof-cof.) was so slow and so heavy that we lost 5~10 seconds of a frozen loading screen, and sometimes we suffered the OS task-kill, all because this method was loading **ALL files/documents at once without any kind of optimization**, this almost killed the phone if the directory had thousands of files, which is acceptable, some directories have a considerable collection of images, texts, videos, etc. But now is possible to load each file lazily through `Stream` Dart APIs, which means we can first load 5 files, then, if needed (through user scroll, user interation, etc), we can load more 5 items.

_Be aware: The current usage can be considered hard to use, because the native API itself isn't friendly, but in a near future we can create separated packages that abstract a set of use-cases to make easier to implement inside Flutter apps_

### CODE REVIEW

File: lib/src/saf/document_file.dart [hunk 1]
```diff
@@ -32,68 +39,128 @@ class DocumentFile {
...
+  /// Path, URI, location of this document, it can exists or not
   final Uri uri;
+
+  /// Whether this document is a directory or not
   final bool isDirectory;
+
+  /// Whether this document is a file or not
   final bool isFile;
+
+  /// Whether this document is a virtual file or not
```
Comment (lakscastro) [inline lib/src/saf/document_file.dart:57]: Missing references and explanation, this doc is heavily redundant

File: android/build.gradle [hunk 2]
```diff
@@ -31,15 +31,17 @@ android {
         main.java.srcDirs += 'src/main/kotlin'
     }
     defaultConfig {
-        minSdkVersion 16
+        minSdkVersion 19
```
Comment (lakscastro) [inline android/build.gradle:34]: Breaking change

**Comment by lakscastro** [comment]
@all-contributors please add @lakscastro for code, doc, maintenance, review

**Comment by lakscastro** [comment]
@all-contributors please add @lakscastro for code, doc, maintenance

**Comment by lakscastro** [comment]
@all-contributors please add @lakscastro for code, doc, maintenance, review

**Comment by lakscastro** [comment]
@all-contributors please add @lakscastro for code, doc, maintenance, review

**Comment by lakscastro** [comment]
@all-contributors please add @lakscastro for code, doc, maintenance, review

**Comment by lakscastro** [comment]
@all-contributors please add @lakscastro for code, maintenance, doc

**Comment by lakscastro** [comment]
@all-contributors please add ankitparmar007 for bug

**Comment by lakscastro** [comment]
@all-contributors please add aplicatii-romanesti, daentech for code

**Comment by lakscastro** [comment]
@all-contributors please add "aplicatii-romanesti", "daentech" for code

**Comment by lakscastro** [comment]
@all-contributors please add aplicatii-romanesti for code

**Comment by lakscastro** [comment]
@all-contributors please add @aplicatii-romanesti for code, bug, ideas

File: android/src/main/kotlin/io/lakscastro/sharedstorage/environment/EnvironmentApi.kt [hunk 3]
```diff
@@ -45,16 +40,12 @@ class EnvironmentApi(val plugin: SharedStoragePlugin) : MethodChannel.MethodCall
...
-  /**
-   * Deprecated Android API, use only if you know exactly what you need
-   */
-  private fun getExternalStoragePublicDirectory(
-    result: MethodChannel.Result,
-    directory: String
-  ) = result.success(environmentDirectoryOf(directory).absolutePath)
+  /** Deprecated Android API, use only if you know exactly what you need */
+  private fun getExternalStoragePublicDirectory(result: MethodChannel.Result, directory: String) =
+      result.success(environmentDirectoryOf(directory).absolutePath)
```
Comment (lakscastro) [inline android/src/main/kotlin/io/lakscastro/sharedstorage/environment/EnvironmentApi.kt:45]: Why aren't marking this as deprecated?

File: android/src/main/kotlin/io/lakscastro/sharedstorage/plugin/Common.kt [hunk 4]
```diff
@@ -4,13 +4,25 @@ import android.os.Build
...
 ) {
   error(
-    EXCEPTION_NOT_SUPPORTED,
-    "Unsupported API. Current API: ${Build.VERSION.SDK_INT} | Required: $minSdk",
-    mapOf("method" to method, *debug.toList().toTypedArray())
+      EXCEPTION_NOT_SUPPORTED,
+      "Unsupported API. Current API: ${Build.VERSION.SDK_INT} | Required: $minSdk",
+      mapOf("method" to method, *debug.toList().toTypedArray())
   )
 }
```
Comment (lakscastro) [inline android/src/main/kotlin/io/lakscastro/sharedstorage/plugin/Common.kt:16]: See [ktfmt](https://facebookincubator.github.io/ktfmt/)
